name: Labeler
on: [pull_request]

jobs:
  design:
    - static/*

  core: flask-heroku-example/**.py

    runs-on: ubuntu-latest

    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

